"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app -A
"""

from setuptools import setup
import os
import zipfile

import app

APP = ['app.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    version=str(app.VERSION)
)


target_dir = 'dist'
zip = zipfile.ZipFile('ZhiHu-MacOS-' + str(app.VERSION) + '.zip', 'w', zipfile.ZIP_DEFLATED)
rootlen = len(target_dir) + 1
for base, dirs, files in os.walk(target_dir):
    for file in files:
        fn = os.path.join(base, file)
        zip.write(fn, fn[rootlen:])